### ISSUE TITLE
Conform to common git commit message style

### ISSUE THREAD

**Issue by dhilgarth** [jaspernbrouwer/git-flow-hooks#10]
git commit messages should be in the imperative mood ([source](http://git.kernel.org/cgit/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n112)).

Please change the commit message when bumping the version number.

**Comment by dhilgarth** [comment]
Please disregard the first commit. It isn't contained in the [PR](#11)

**Comment by jaspernbrouwer** [comment]
I've met your change in the commit messages, and raised you a config setting to customize that message ;) See 001d8952ca3d93fabc6f648ec7b54a1b17b81dd8.
