### ISSUE TITLE
Info: Chocolatey package

### ISSUE THREAD

**Issue by dhilgarth** [jaspernbrouwer/git-flow-hooks#12]
For the Windows folks in here, I created a Chocolatey package:
https://chocolatey.org/packages/gitflow-hooks

The source code is here: https://github.com/dhilgarth/chocolatey-packages/tree/master/manual/gitflow-hooks.

**Comment by jaspernbrouwer** [comment]
I assume you've checked, and I'm surprised this package even works on Windows, I guess that's a good thing!

I don't know Chocolatey, but I see the package is under moderation. If it can't be used as such, maybe you could ping me when it's approved? Then I could add something to the README.

> This package always installs the latest version, so the package version will always be 0.0.0.

This sounds a bit weird to me. I don't like it, but can't find the right words to explain why. IMHO the metadata for a package-manager should follow the version (and anything else) of the packages itself.

**Comment by dhilgarth** [comment]
Which package do you mean? git-flow-hooks? Yes, it is working on Windows, I have been using it for over a year now.  
Chocolatey is a package manager for windows similar to apt-get. Unfortunately, the folks over there currently take a long time to approve a package - they just won a kickstarter campaign some time back and introduced moderation at the same time. They are basically buried in work. I hope this fill be a thing of the past.

Anyway, I very much would like to follow your versioning, but so far, I don't really see any in the repository :-)
So, if you introduce versions and add a version tag for each new version, I will change the package to follow the versioning of this repository.

**Comment by dhilgarth** [comment]
@jaspernbrouwer I just changed the package to be in sync with the releases of this repository.  
Whenever you release a new version it will automatically create a new package version in Chocolatey.  
The package also now has a parameter that allows the user to decide whether git-flow-hooks should be installed globally or not.
https://chocolatey.org/packages/git-flow-hooks/1.0.1

If you approve of these changes and the package in general, could you please explicitly state so? This might help in getting the package approved faster.

**Comment by jaspernbrouwer** [comment]
If you like to maintain the package on Chocolatey, by all means proceed! It looks good, I see the sync is functioning, so I approve :smile:

**Comment by dhilgarth** [comment]
Thanks :)
