### ISSUE TITLE
Merge markers detected in binary file

### ISSUE THREAD

**Issue by dhilgarth** [jaspernbrouwer/git-flow-hooks#13]
The implementation of https://github.com/jaspernbrouwer/git-flow-hooks/blob/master/modules/prevent-merge-marker-commits.sh is too simplistic.  
It detects merge markers in binary files.

See also: http://stackoverflow.com/questions/33450379/git-incorrectly-detects-merge-markers-in-binary-file-on-commit

**Comment by jaspernbrouwer** [comment]
I see 2 ways forward:

1. Make detection of the merge markers more elaborate, like searching for `<<<<<<<`, `=======` and `>>>>>>>` in that order.
2. Simply ignoring binary files.

Any thoughts?

**Comment by dhilgarth** [comment]
I would say #2 is sufficient. There shouldn't be any case when binary files contain real merge markers

**Comment by jaspernbrouwer** [comment]
This issue should be fixed in 2bd0ef9f975cb0cb25791189c1ffaae63f30815c.
Sorry it took ages!
