### ISSUE TITLE
release start  can't  bump a auto version

### ISSUE THREAD

**Issue by zhou-yg** [jaspernbrouwer/git-flow-hooks#14]
on centos,

   >  git clone git@github.com:jaspernbrouwer/git-flow-hooks.git

   >  git flow init

   >  git config gitflow.path.hooks git-flow-hooks/

   > git config gitflow.hotfix.finish.message "Hotfix %tag%"

   > git config gitflow.release.finish.message "Release %tag%"

   > git flow release start    // error: Missing argument < version >

is any wrong in these steps ?

**Comment by jaspernbrouwer** [comment]
Sorry it took so long to get back at you!

`git flow init` and `git flow release start` should be run from within a working copy. Are you doing that?

**Comment by jaspernbrouwer** [comment]
Closing this because of a lack of response.
