### ISSUE TITLE
can not clone. Permition denied

### ISSUE THREAD

**Issue by KES777** [jaspernbrouwer/git-flow-hooks#16]
```
 git clone git@github.com:jaspernbrouwer/git-flow-hooks.git
Cloning into 'git-flow-hooks'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
So I change clone command:

    git clone https://github.com/jaspernbrouwer/git-flow-hooks

Please update your DOC

**Comment by jaspernbrouwer** [comment]
> Permission denied (publickey).

This is a problem on your end I'm afraid. Github is not accepting your SSH key.
Please see the [Github Help on this subject][1] to resolve the issue.

PS: You're free to use HTTPS instead of SSH to clone of course!

[1]: https://help.github.com/articles/error-permission-denied-publickey/

**Comment by KES777** [comment]
No, this is the problem at [your doc](https://github.com/jaspernbrouwer/git-flow-hooks/blame/master/README.md#L23). You advice to clone in that way. I just copy-paste.

Please change that line to:

    git clone https://github.com/jaspernbrouwer/git-flow-hooks

PS. If you think that is not problem. Leave that as is.
