### ISSUE TITLE
Multiline tag message

### ISSUE THREAD

**Issue by Kitzberger** [jaspernbrouwer/git-flow-hooks#18]
Is it possible to create multiline tag messages? I'd like to introduce a new tag message variable to be replaced by a multiline text when finishing a release. Unfortunately all of the line breaks (\n) seem to get lost on the way from format-tag-message.sh to the actual tag message.

Maybe you can give me a push into the right direction ;-)

**Comment by jaspernbrouwer** [comment]
Hmm... It wasn't built with multi-line in mind, but I see no reason why it shouldn't work. I'll look into that.

Can you give a sample of what message you put in and how it comes out?

**Comment by jaspernbrouwer** [comment]
Closing this because of a lack of response.
