### ISSUE TITLE
Version bump doesn't work

### ISSUE THREAD

**Issue by marcinant** [jaspernbrouwer/git-flow-hooks#5]
I use Ubuntu 15.04 with 'git flow 1.8.0 (AVH Edition)'.

README says: 
>If git flow release start and git flow hotfix start are run without a version, the version will be bumped automatically.

However when I try to start release without version number then I get this:
'fatal: 'release/.0.1' is not a valid branch name.
Fatal: Could not create release branch 'release/.0.1''

**Comment by marcinant** [comment]
I've found small workaround. When I run:
'git flow release start 0'

Then version is detected and bumped correctly.

**Comment by jaspernbrouwer** [comment]
Version bumping is done based on a version file. This file defaults to `VERSION` in the root of the working-copy and contains the current version (the version to be bumped). If the file doesn't exist yet, it should fall back to `1.0.0`.

So did the file exist in your case?
If so, what was the content of that file?

**Comment by marcinant** [comment]
Well. No. However:
>The hooks will look at the git tags to find the version to bump. If no tags are found, it looks for the version-file. If that isn't found, it assumes the current version is 0.0.0

There is no 'version-file' in my project indeed. But as described above: version should be detected from git tags and this is where it fails.

**Comment by jaspernbrouwer** [comment]
Sorry, you're right, `0.0.0` is the one used if no current version is found. So `0.0.1` would be the end result in that case.

But I need some info to figure out where it's going wrong.

Could you run the following commands within the root of your working-copy?

```bash
PREFIX=$(git config --get gitflow.prefix.versiontag)
echo $PREFIX
git tag -l "$PREFIX*"
git rev-parse --show-toplevel
```

And show me the output?

**Comment by marcinant** [comment]
Ok. I see. Version tag is empty and $PREFIX is empty too.
While I got some releases:
```

0.0.26
0.0.27
0.0.28
0.0.29
0.0.30
0.0.31
0.0.32
0.0.33
0.0.34
0.0.35
0.0.36
```

**Comment by jaspernbrouwer** [comment]
An empty version-tag should be fine, and the actual tags in git match that.

One last question: do you have `gsort` on your system, or `sort` that supports the `-V` option? If so, where is it located (absolute path)?

I'll look into using an empty version-tag, see if that causes the issue.

**Comment by marcinant** [comment]
My system is Ubuntu 15.04.
There is no 'gsort'. 'sort' is available and supports the '-V' option: '--version-sort'.
Its location is: '/usr/bin/sort'

**Comment by jaspernbrouwer** [comment]
Thanks! I'll get back to you.

**Comment by marcinant** [comment]
Thank you for quick response.

BTW there is another thing I would like to mention.
IMHO there is a better and more elegant way to install your hooks.

I think that you could consider a small refactoring on your project and move hooks to /hooks dir.
Then your hooks could be installed with `git init --template=<template_directory>` where `<template_directory>` is folder with this project repo cloned from github.

In this way there is no need to delete or symlink hooks folder.

**Comment by jaspernbrouwer** [comment]
Could you open a new issue for this (and remove it here)? That way I can keep track of individual stories :smile:

**Comment by marcinant** [comment]
Ok. Another info... I created new empty project repo and copied your hooks and version was detected as `0.1.0` and just bumped this to `0.2.0`.

Unfortunately it still doesn't work on any of my existing repositories which contains some release tags with versions like `0.0.20`.

**Comment by jaspernbrouwer** [comment]
I can't reproduce the issue :(

I've created an empty directory, run `git init` and `git flow init`, created the tags `0.0.34`, `0.0.35` and `0.0.36`. I'm _not_ using a version prefix.

When I run `git flow hotfix start`, the version is correctly bumped to `0.0.37`.
When I run `git flow release start`, the version is correctly bumped to `0.1.0`.

Are you sure that _all_ tags are following semver (`<major>.<minor>.<patch>`)? Or is there a tag in there that has a different structure?

**Comment by jaspernbrouwer** [comment]
I've also tested it on a Debian machine (the previous comment was on an OS X machine), but I still can't reproduce the issue :(

Are you sure that all tags are following semver (`<major>.<minor>.<patch>`)? Or is there a tag in there that has a different structure?

Also, can you test the semverbump manually? `/path/to/git-flow-hooks/modules/semverbump.sh minor`

And maybe you can do some debugging yourself by placing `echo` statements at certain points in the script (e.g. right after a variable is declared to echo the value of that variable), then run `/path/to/git-flow-hooks/modules/semverbump.sh minor`. See if you can find some strange results, that would help me a lot.

PS: I have a very limited bandwidth internet connection for the next month, so downloading and setting up an Ubuntu 15.04 virtual machine isn't an option at the moment :(

**Comment by marcinant** [comment]
Ok. Let's close this issue. Problem was that hooks weren't available on each branch.
