### ISSUE TITLE
Allow global git-flow-hooks-config.sh

### ISSUE THREAD

**Issue by dhilgarth** [jaspernbrouwer/git-flow-hooks#9]
I want your hooks to be available in every local repository, existing or created in the future.
Generally, it's very easy to achieve this by globally setting gitflow.path.hooks.

What doesn't work is a global customization for all projects. For example, my version file always sits at `version/version.txt`. Right now, I need to create a `git-flow-hooks-config.sh` in each repository to perform this customization.

**Comment by jaspernbrouwer** [comment]
I agree a global config file should be possible.

I propose the following:

- First load `git-flow-hooks-config.sh` from the hooks directory itself, which would act as global configuration.
- Then load `git-flow-hooks-config.sh` from the root directory (of the repository), which would act as local configuration. Any local settings would override the global ones.

Would this solve your issue?

**Comment by dhilgarth** [comment]
Perfect, exactly what I was thinking

**Comment by jaspernbrouwer** [comment]
Done! See 35df74bfba90c26f38e9c270916c2ca00453a6fa.

**Comment by dhilgarth** [comment]
Thank you!
